version: '3.3'
services:
  mongo:
    container_name: openhim-mongo
    restart: always
    ports:
    - 27017:27017
    image: mongo:3.4 
    environment:
    - MONGO_INITDB_ROOT_USERNAME_FILE=/var/lib/openhim/mongo_root_user
    - MONGO_INITDB_ROOT_PASSWORD_FILE=/var/lib/openhim/mongo_root_password
    - MONGO_INITDB_USERNAME_FILE=/var/lib/openhim/mongo_user
    - MONGO_INITDB_PASSWORD_FILE=/var/lib/openhim/mongo_password
    volumes:
     - /var/lib/consolidated-server/mongodata:/data/db
     - ./prod/database/mongo/init/:/docker-entrypoint-initdb.d/
     - ./prod/database/mongo/db_root_user:/var/lib/openhim/mongo_root_user
     - ./prod/database/mongo/db_root_password:/var/lib/openhim/mongo_root_password
     - ./prod/database/mongo/db_user:/var/lib/openhim/mongo_user
     - ./prod/database/mongo/db_password:/var/lib/openhim/mongo_password
    networks:
    - backend-network
    
  openhim-core:
    container_name: openhim-core
    restart: always
    image: jembi/openhim-core
    env_file:
    - prod/properties/openhim.env
    ports:
    - 8080:8080
    - 5000:5000
    - 5001:5001
    - 5050:5050
    - 5051:5051
    - 5052:5052
    - 7788:7788
    depends_on:
    - mongo
    volumes:
    - ./prod/properties/openhim-core_default.json:/usr/src/app/config/default.json
    networks:
    - frontend-network
    - backend-network
    
  #accessed through nginx container
  openhim-console:
    container_name: openhim-console
    restart: always
    image: jembi/openhim-console
    volumes:
    - ./prod/conf/nginx_openhim-console.conf:/etc/nginx/conf.d/default.conf
    - ./prod/ssl/lf.crt:/etc/nginx/serverCerts/lf.crt
    - ./prod/ssl/lf.key:/etc/nginx/serverCerts/lf.key
    - ./prod/ssl/key_pass:/etc/nginx/private/key_pass
    - ./prod/properties/openhim-console_default.json:/usr/share/nginx/html/config/default.json
    networks:
    - frontend-network
    - backend-network
    
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
    - 9080:80
    - 9443:443
    volumes:
    - ./prod/conf/nginx_main.conf:/etc/nginx/conf.d/default.conf
    - ./prod/ssl/lf_frontend.crt:/etc/nginx/serverCerts/oh.crt
    - ./prod/ssl/lf_frontend.key:/etc/nginx/serverCerts/oh.key
    - ./prod/ssl/key_pass_frontend:/etc/nginx/private/key_pass
    networks:
    - frontend-network
    
networks:
  frontend-network: 
  backend-network: 
